# Generated by Django 6.0.4 on 2026-05-10 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_name', models.CharField(help_text='Nome del csv', max_length=255)),
                ('step', models.FloatField(help_text='Passo tra i campioni (es. 0.02 s)')),
                ('time_values', models.JSONField(help_text='Lista dei valori di tempo [0, 0.02, ...]')),
                ('voltage_values', models.JSONField(help_text='Lista dei valori di tensione [0, 0.1, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rects', models.JSONField()),
                ('trapezius', models.JSONField()),
                ('simpson', models.JSONField()),
                ('result_rectangles', models.FloatField()),
                ('result_trapezius', models.FloatField()),
                ('result_simpson', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='calculator.dataset')),
            ],
        ),
    ]
