# Generated by Django 6.0.4 on 2026-05-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='curve',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
