# Generated by Django 6.0.4 on 2026-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_calculation_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='v_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
